---
title: "PSTAT 10 Worksheet 9"
output:
  pdf_document:
    latex_engine: xelatex
---

## Setup
```{r}
setwd('G:/Documents/School/2023-2024/Summer 2024/PSTAT 10/PSTAT10-Worksheets-and-HW')
library(tidyverse)
hibbs <- as_tibble(read.csv("hibbs.dat", sep=" "))
```


## Problem 1
```{r}
plot <- ggplot(hibbs, mapping = aes(x = growth, y = vote))
plot + geom_smooth(method='lm', se= FALSE, col="red") +
       geom_hline(yintercept=50, col="gray") + 
       geom_point() +
       ggrepel::geom_text_repel(data=NULL, mapping = aes(x = growth, y = vote, label=year)) +
       guides(fill = "none") +
       labs(x = "Avg. recent growth in personal income", y = "Incumbent party's vote share", 
            title = "Bread and Peace",subtitle = "Forecasting the election from the economy", 
            caption= "Source: Douglas Hibbs") +
       scale_x_continuous(breaks=c(0,1,2,3,4), labels=c('0%','1%','2%','3%','4%')) +
       scale_y_continuous(breaks=c(45,50,55,60), labels=c('45%','50%','55%','60%')) +
       theme_classic()

```

## Problem 2
```{r}
p <- ggplot(mpg, mapping = aes(x = cyl, y = hwy))
p + geom_boxplot(mapping=aes(group=cyl))
```

## Problem 3
```{r}
library(babynames)
robin <- filter(babynames, name == "Robin")
robin_plot <- ggplot(robin, mapping = aes(x = year, y = n, color=sex))
robin_plot + geom_line() +
             guides(fill = "Sex") +
             labs(x = "Year", y = "Number", title = "Number of babies named Robin", caption = "Source: SSA")
```