---
title: "Homework 5"
output: pdf_document
---

# Setup
```{r}
library(tidyverse)
library(datasets)
library(scales)
library(ggrepel)
```

# Problem 1
```{r}
aqdata <- as_tibble(airquality)
tempData1 <- aqdata |> filter(Temp >= 80) |> mutate(Feels = 'Hotter')
tempData2 <- aqdata |> filter(Temp < 80) |> mutate(Feels = 'Colder') 
aqdata <- rbind(tempData1, tempData2)
plot <- ggplot(aqdata, mapping = aes(x = Wind, y = Ozone, color=Feels))
plot + geom_point(aes()) +
       geom_smooth(method='lm', se = TRUE, col='#3366ff') +
       scale_color_manual(values = c("Colder" = "cadetblue3", "Hotter" = "tomato"), name=NULL) +
       labs(x = 'Wind (mph)', y = 'Ozone (ppb)', title='Ozone and Wind in NYC, 1973') +
       guides(fill=guide_legend(title='test')) +
       theme_classic() 
```

# Problem 2
```{r}
checkDerange <- function(sequence)
{
       for(i in 1:length(sequence))
       {
              if(i == sequence[i])
              {
                     return(FALSE)
              }
       }
       return(TRUE)
}

trial <- function(numReps)
{
       values <- replicate(n=numReps, sample(1:100))
       isDerange = c()
       for(i in 1:numReps)
       {
              isDerange[i] = checkDerange(values[,i])
       }
       return(sum(isDerange)/length(isDerange))
}


plot_values = c()
for(i in 1:2000)
{
       plot_values[i] = trial(i)
}
plot_x = 1:2000
plot_2_df <- data.frame(plot_x, plot_values)

plot_2 <- ggplot(plot_2_df, mapping=aes(x = plot_x, plot_values))
plot_2 + geom_line() +
         geom_hline(yintercept=0.368, col='red') +
         labs(x = 'Number of replications', y = 'p', title = 'Probability of a derangement') +
         theme_classic() +
         coord_cartesian(ylim = c(0, 1.0)) 
```

# Problem 3
```{r}
who_tidy <- who |>
  pivot_longer(cols = new_sp_m014:newrel_f65,
               names_to = "key",
               values_to = "cases",
               values_drop_na = TRUE) |>
  mutate(key = stringr::str_replace(key, "newrel", "new_rel")) |>
  separate(key, c("new", "type", "sexage"), sep = "_") |>
  select(-new, -iso2, -iso3) |>
  separate(sexage, c("sex", "age"), 1)
who_tidy

plot_3_tb <- who_tidy |> group_by(country, year, sex) |> summarise(numCases=sum(cases))
plot_3 <- ggplot(plot_3_tb, mapping=aes(x=year, y=numCases)) 
plot_3 + geom_jitter(aes(group=country), width=0.3, alpha=0.2) +
         geom_text_repel(data=filter(plot_3_tb, country=='India', year==2007), col='red', vjust=0, label='India 2007') +
         facet_wrap(~sex, labeller=labeller(sex = c('f' = 'Women','m' = 'Men'))) +
         coord_cartesian(ylim=(c(0,800000))) +
         scale_y_continuous(labels=label_comma()) +
         scale_x_continuous(breaks = seq(1980, 2015, by = 5)) +
         labs(x='', y='Total Cases', title = 'Tubercolosis Cases in Countries by Year',
              subtitle = 'Dramatic increase in case count since mid 90s', caption = 'Source: World Health Organizations')
```

## Problem 4

**Part 1**
The main issue with this dataset is that the column headers are values rather than variables. A tidy dataset would hold the values of these column headers under one variable/column.

**Part 2**
```{r}
relig_income_tidy <- relig_income |> pivot_longer(cols = c('<$10k', '$10-20k', '$20-30k', '$30-40k', '$40-50k', '$50-75k', '$75-100k'), 
                                                  names_to = "income",
                                                  values_to = "frequency") |>
                                     select(religion, income, frequency)
```

**Part 3**
```{r}
plot_4 <- ggplot(relig_income_tidy, mapping=aes(x=frequency, y=reorder(religion, frequency), fill=religion))
plot_4  + geom_col() +
          guides(fill="none") +
          coord_cartesian(xlim=(c(0,7500))) +
          scale_x_continuous(breaks = seq(0,7500, by=2500)) +
          labs(x = '', y = '', title = 'Participants in Pew Research Survey', caption = 'Source: Pew Research Center') +
          theme_minimal()
```